wandb_version: 1

learning_rate:
  desc: null
  value: 0.0002
batch_size:
  desc: null
  value: 16
optimizer:
  desc: null
  value: adamw_bnb_8bit
lr_scheduler_type:
  desc: null
  value: constant
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.17.9
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725943173
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      - 98
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      - 98
      3:
      - 13
      - 16
      - 23
      4: 3.11.6
      5: 0.17.9
      6: 4.44.2
      8:
      - 3
      - 5
      12: ''
      13: windows-amd64
